/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Perpustakaan;

import java.awt.Color;
import Perpustakaan.MenuPeminjaman;

/**
 *
 * @author ASUS
 */
public class MenuDasboard extends javax.swing.JFrame {
    private MenuPeminjaman parent;
    /**
     * Creates new form MenuDasboard
     */
    public MenuDasboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pn_anggota = new javax.swing.JPanel();
        pn_lineanggota = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_anggota = new javax.swing.JLabel();
        pn_admin = new javax.swing.JPanel();
        pn_lineadmin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_admin = new javax.swing.JLabel();
        pn_buku = new javax.swing.JPanel();
        pn_linebuku = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_buku = new javax.swing.JLabel();
        pn_pengembalian = new javax.swing.JPanel();
        pn_linepengembalian = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_pengembalian = new javax.swing.JLabel();
        pn_peminjaman = new javax.swing.JPanel();
        pn_linepeminjaman = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_peminjaman = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        pn_atas1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("AdminLib");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bukulogo.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("MASTER DATA");

        pn_anggota.setBackground(new java.awt.Color(255, 255, 255));

        pn_lineanggota.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_lineanggotaLayout = new javax.swing.GroupLayout(pn_lineanggota);
        pn_lineanggota.setLayout(pn_lineanggotaLayout);
        pn_lineanggotaLayout.setHorizontalGroup(
            pn_lineanggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_lineanggotaLayout.setVerticalGroup(
            pn_lineanggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/petugaspinky.png"))); // NOI18N

        btn_anggota.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_anggota.setForeground(new java.awt.Color(102, 102, 102));
        btn_anggota.setText("Anggota");
        btn_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_anggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_anggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_anggotaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_anggotaLayout = new javax.swing.GroupLayout(pn_anggota);
        pn_anggota.setLayout(pn_anggotaLayout);
        pn_anggotaLayout.setHorizontalGroup(
            pn_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_anggotaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pn_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_anggotaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lineanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(184, Short.MAX_VALUE)))
        );
        pn_anggotaLayout.setVerticalGroup(
            pn_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_anggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addGroup(pn_anggotaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_anggota)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pn_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_anggotaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lineanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_admin.setBackground(new java.awt.Color(255, 255, 255));

        pn_lineadmin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_lineadminLayout = new javax.swing.GroupLayout(pn_lineadmin);
        pn_lineadmin.setLayout(pn_lineadminLayout);
        pn_lineadminLayout.setHorizontalGroup(
            pn_lineadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_lineadminLayout.setVerticalGroup(
            pn_lineadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/petugaspinky.png"))); // NOI18N

        btn_admin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_admin.setForeground(new java.awt.Color(102, 102, 102));
        btn_admin.setText("Admin");
        btn_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_adminMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_adminLayout = new javax.swing.GroupLayout(pn_admin);
        pn_admin.setLayout(pn_adminLayout);
        pn_adminLayout.setHorizontalGroup(
            pn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_adminLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_adminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lineadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(184, Short.MAX_VALUE)))
        );
        pn_adminLayout.setVerticalGroup(
            pn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addGroup(pn_adminLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_admin)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_adminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_lineadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_buku.setBackground(new java.awt.Color(255, 255, 255));

        pn_linebuku.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_linebukuLayout = new javax.swing.GroupLayout(pn_linebuku);
        pn_linebuku.setLayout(pn_linebukuLayout);
        pn_linebukuLayout.setHorizontalGroup(
            pn_linebukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_linebukuLayout.setVerticalGroup(
            pn_linebukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bukupinky.png"))); // NOI18N

        btn_buku.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_buku.setForeground(new java.awt.Color(102, 102, 102));
        btn_buku.setText("Buku");
        btn_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_bukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_bukuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_bukuLayout = new javax.swing.GroupLayout(pn_buku);
        pn_buku.setLayout(pn_bukuLayout);
        pn_bukuLayout.setHorizontalGroup(
            pn_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_bukuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_bukuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(209, Short.MAX_VALUE)))
        );
        pn_bukuLayout.setVerticalGroup(
            pn_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_bukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addGroup(pn_bukuLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_buku)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pn_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_bukuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_pengembalian.setBackground(new java.awt.Color(255, 255, 255));

        pn_linepengembalian.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_linepengembalianLayout = new javax.swing.GroupLayout(pn_linepengembalian);
        pn_linepengembalian.setLayout(pn_linepengembalianLayout);
        pn_linepengembalianLayout.setHorizontalGroup(
            pn_linepengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_linepengembalianLayout.setVerticalGroup(
            pn_linepengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pengembalianpinky.png"))); // NOI18N

        btn_pengembalian.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_pengembalian.setForeground(new java.awt.Color(102, 102, 102));
        btn_pengembalian.setText("Pengembalian");
        btn_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_pengembalianLayout = new javax.swing.GroupLayout(pn_pengembalian);
        pn_pengembalian.setLayout(pn_pengembalianLayout);
        pn_pengembalianLayout.setHorizontalGroup(
            pn_pengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pengembalianLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pn_pengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_pengembalianLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linepengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(184, Short.MAX_VALUE)))
        );
        pn_pengembalianLayout.setVerticalGroup(
            pn_pengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_pengembalianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_pengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addGroup(pn_pengembalianLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_pengembalian)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pn_pengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_pengembalianLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linepengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_peminjaman.setBackground(new java.awt.Color(255, 255, 255));

        pn_linepeminjaman.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_linepeminjamanLayout = new javax.swing.GroupLayout(pn_linepeminjaman);
        pn_linepeminjaman.setLayout(pn_linepeminjamanLayout);
        pn_linepeminjamanLayout.setHorizontalGroup(
            pn_linepeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_linepeminjamanLayout.setVerticalGroup(
            pn_linepeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/peminjamanpinky.png"))); // NOI18N

        btn_peminjaman.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_peminjaman.setForeground(new java.awt.Color(102, 102, 102));
        btn_peminjaman.setText("Peminjaman");
        btn_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_peminjamanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_peminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_peminjamanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_peminjamanLayout = new javax.swing.GroupLayout(pn_peminjaman);
        pn_peminjaman.setLayout(pn_peminjamanLayout);
        pn_peminjamanLayout.setHorizontalGroup(
            pn_peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_peminjamanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pn_peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_peminjamanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linepeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(184, Short.MAX_VALUE)))
        );
        pn_peminjamanLayout.setVerticalGroup(
            pn_peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_peminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addGroup(pn_peminjamanLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_peminjaman)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pn_peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_peminjamanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_linepeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_kiriLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3)))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pn_buku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pn_admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(pn_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        pn_atas1.setBackground(new java.awt.Color(102, 0, 51));

        javax.swing.GroupLayout pn_atas1Layout = new javax.swing.GroupLayout(pn_atas1);
        pn_atas1.setLayout(pn_atas1Layout);
        pn_atas1Layout.setHorizontalGroup(
            pn_atas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        pn_atas1Layout.setVerticalGroup(
            pn_atas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        pn_utama.add(pn_atas1, java.awt.BorderLayout.PAGE_START);

        pn_kanan.add(pn_utama, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMouseEntered
        pn_anggota.setBackground(new Color(250,250,250));
        pn_lineanggota.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_anggotaMouseEntered

    private void btn_anggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMouseExited
        pn_anggota.setBackground(new Color(255,255,255));
        pn_lineanggota.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_anggotaMouseExited

    private void btn_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseEntered
        pn_admin.setBackground(new Color(250,250,250));
        pn_lineadmin.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_adminMouseEntered

    private void btn_adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseExited
        pn_admin.setBackground(new Color(255,255,255));
        pn_lineadmin.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_adminMouseExited

    private void btn_bukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukuMouseEntered
        pn_buku.setBackground(new Color(250,250,250));
        pn_linebuku.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_bukuMouseEntered

    private void btn_bukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukuMouseExited
        pn_buku.setBackground(new Color(255,255,255));
        pn_linebuku.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_bukuMouseExited

    private void btn_pengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseEntered
        pn_pengembalian.setBackground(new Color(250,250,250));
        pn_linepengembalian.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_pengembalianMouseEntered

    private void btn_pengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseExited
        pn_pengembalian.setBackground(new Color(255,255,255));
        pn_linepengembalian.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_pengembalianMouseExited

    private void btn_peminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMouseEntered
        pn_peminjaman.setBackground(new Color(250,250,250));
        pn_linepeminjaman.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_peminjamanMouseEntered

    private void btn_peminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMouseExited
        pn_peminjaman.setBackground(new Color(255,255,255));
        pn_linepeminjaman.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_peminjamanMouseExited

    private void btn_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMouseClicked
        pn_peminjaman.setBackground(new Color(240,240,240));
        pn_linepeminjaman.setBackground(new Color(0,102,153));
        
        this.setVisible(false); // Menyembunyikan form login
        new MenuAnggota().setVisible(true);
    }//GEN-LAST:event_btn_anggotaMouseClicked

    private void btn_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMouseClicked
        pn_peminjaman.setBackground(new Color(240,240,240));
        pn_linepeminjaman.setBackground(new Color(0,102,153));
        
        this.setVisible(false); // Menyembunyikan form login
        new MenuPeminjaman().setVisible(true);

    }//GEN-LAST:event_btn_peminjamanMouseClicked

    private void btn_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseClicked
        pn_pengembalian.setBackground(new Color(240,240,240));
        pn_linepengembalian.setBackground(new Color(0,102,153));
        
        this.setVisible(false); // Menyembunyikan form login
        new MenuPengembalian().setVisible(true);
    }//GEN-LAST:event_btn_pengembalianMouseClicked

    private void btn_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseClicked
        pn_admin.setBackground(new Color(240,240,240));
        pn_lineadmin.setBackground(new Color(0,102,153));
        
        this.setVisible(false); // Menyembunyikan form login
        new MenuAdmin().setVisible(true);
    }//GEN-LAST:event_btn_adminMouseClicked

    private void btn_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukuMouseClicked
        pn_buku.setBackground(new Color(240,240,240));
        pn_linebuku.setBackground(new Color(0,102,153));
        
        this.setVisible(false); // Menyembunyikan form login
        new MenuBuku().setVisible(true);
    }//GEN-LAST:event_btn_bukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDasboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_admin;
    private javax.swing.JLabel btn_anggota;
    private javax.swing.JLabel btn_buku;
    private javax.swing.JLabel btn_peminjaman;
    private javax.swing.JLabel btn_pengembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pn_admin;
    private javax.swing.JPanel pn_anggota;
    private javax.swing.JPanel pn_atas1;
    private javax.swing.JPanel pn_buku;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_lineadmin;
    private javax.swing.JPanel pn_lineanggota;
    private javax.swing.JPanel pn_linebuku;
    private javax.swing.JPanel pn_linepeminjaman;
    private javax.swing.JPanel pn_linepengembalian;
    private javax.swing.JPanel pn_peminjaman;
    private javax.swing.JPanel pn_pengembalian;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
